name: "gts"
mode: "dev"
version: "v1.0.0"
start_time: "2023-3-17"
ip: "0.0.0.0"
port: 7777
ip_version: "tcp4"
max_conn: 3000 # 最大连接数
max_packet_size: 4096 # 数据包最大大小
worker_pool_size: 100 # 业务工作Worker池的数量
max_worker_task_len: 1024 # 业务工作Worker对应负责的任务队列最大任务存储数量